@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Editar Simulación - FISC


REPORTE -[#green]-> :editar_simulacion 
note on link
  **Usuario solicita:**
  - Editar simulación
end note
  
:editar_simulacion -[#green]-> CONFIGURACIÓN_DE_SIMULACIÓN

@enduml