@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Cancelar Simulación - FISC


SIMULANDO-[#green]-> cancelar_simulación
note on link
  **Usuario solicita:**
  - Cancelar simulación
end note

state cancelar_simulación{
   state 1 as " "
   state 2 as " "
   state 3 as " "

   [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema Requiere:**
      - Estas Seguro?
  end note
  2 -[#green]-> 3
  note on link
      **Usuario Aporta:**
      - Si / No
  end note
  3 -[#green]-> [*]

}
cancelar_simulación -[#green]-> :cancelar_simulación
cancelar_simulación -[#green]-> :seguir_simulando
:seguir_simulando -[#green]-> SIMULANDO

:cancelar_simulación -[#green]-> CONFIGURACIÓN_DE_SIMULACIÓN

@enduml