@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Nuevo Proyecto - FISC


PÁGINA_PRINCIPAL-[#green]-> nuevo_proyecto
note on link
  **Usuario solicita:**
  - Nuevo Proyecto
end note

state nuevo_proyecto{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]->1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Nombre del proyecto
      - Descripción del proyecto (opcional)
  end note
  2 -[#green]-> 3
  note on link
    **Usuario aporta:**
      - Nombre del proyecto
      - Descripción del proyecto (opcional)
  end note
  3 -[#red]-> 1
  note on link
    [nombre de proyecto existente]
  end note
  3 -[#green]-> [*]
}

nuevo_proyecto-[#green]-> :abrirPáginaProyecto

:abrirPáginaProyecto -[#green]-> PÁGINA_PROYECTO

@enduml