@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Inicio de Sesión - FISC


INICIO -[#green]-> iniciar_sesión 
note on link
  **Usuario solicita:**
  - Iniciar sesión
end note

state iniciar_sesión {
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Usuario
      - Contraseña
  end note
  2 -[#green]-> 3
  note on link
    **Usuario aporta:**
    - Usuario
    - Contraseña
  end note
  3 -[#red]-> 1
  note on link
    [usuario y contraseña inexistentes]
  end note
  3 -[#green]-> [*]
}

iniciar_sesión -[#green]-> :abrirPaginaPrincipal

:abrirPaginaPrincipal -[#green]-> PAGINA_PRINCIPAL

@enduml