@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Ver Reporte - FISC


PÁGINA_PROYECTO-[#green]-> ver_reporte
note on link
  **Usuario solicita:**
  - Ver reporte 
end note

state ver_reporte{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Selección de reporte
  end note
  2 -[#green]-> 3
  note on link
    **Usuario selecciona:**
    - Reporte
  end note
  3 -[#green]-> [*]
}

ver_reporte -[#green]-> :abrirReporte

:abrirReporte-[#green]-> REPORTE

@enduml