@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Cancelar Simulación - FISC


SIMULANDO-[#green]-> cancelar_simulación
note on link
  **Usuario solicita:**
  - Cancelar simulación
end note

cancelar_simulación -[#green]-> :abrirConfiguraciónDeSimulación
:abrirConfiguraciónDeSimulación-[#green]-> CONFIGURACIÓN_DE_SIMULACIÓN

@enduml