@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Abrir Proyecto - FISC


PÁGINA_PRINCIPAL -[#green]-> abrir_proyecto
note on link
  **Usuario solicita:**
  - Abrir proyecto
end note

state abrir_proyecto{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Archivo de proyecto conocido
  end note
  2 -[#green]-> 3
  note on link
    **Usuario Selecciona:**
    - Archivo de proyecto conocido
  end note
 
  3 -[#green]-> [*]
}

abrir_proyecto-[#green]-> :abrirPáginaProyecto

:abrirPáginaProyecto -[#green]-> PÁGINA_PROYECTO

@enduml