@startuml

title Caso de Uso Inicio de Sesión - FISC

state INICIO as "INICIO"
state DASHBOARD_ABIERTO as "DASHBOARD_ABIERTO"

INICIO --> iniciar_sesión : el usuario solicita

state iniciar_sesión {
  [*] --> InicioSesión: Usuario elige iniciar sesión
  [*] --> Registro: Usuario elige registrarse 
  Registro --> InicioSesión : puede pasar 
  InicioSesión --> DASHBOARD_ABIERTO : registro correcto
}

note left of Registro
  - El sistema reconoce al nuevo usuario
  - Pasa de "usuario_no_registrado" a "usuario"
end note

note right of InicioSesión{
  - Se inicia sesión con usuario y contraseña
}

@enduml