@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Exportar Simulación - FISC


PÁGINA_PROYECTO -[#green]-> exportar_simulacion 
note on link
  **Usuario solicita:**
  - Exportar simulacion
end note

state exportar_simulacion {
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Simulacion
  end note
  2 -[#green]-> 3
  note on link
    **Usuario Selecciona:**
    - simulacion
  end note
  3 -[#red]-> 1
  note on link
    [Simulacion está vacía]
  end note
  3 -[#green]-> [*]
}

exportar_simulacion -[#green]-> :exportar_simulacion

:exportar_simulacion -[#green]-> PÁGINA_PROYECTO

@enduml