@startuml AlumniModel

title Servicios de Alumni

'!theme amiga
skinparam backgroundColor white
skinparam defaultFontName Arial
hide circle

abstract SERVICIO 
{
    Nombre 
    Descripción
    Precio
    Tipo de Servicio
}

class COMUNICACIÓN 
{
    Email
    Chat
}

SERVICIO <|-- "COMUNICACIÓN"

@enduml