@startuml

title Caso de Uso Simulación - FISC

left to right direction

actor Usuario as user8

rectangle "FISC Simulación" {
  usecase "Volver" as paginaProyecto
  usecase "Importar Simulación existente" as importarExistente
  usecase "Parámetros" as datosSimulacion
  usecase "Iniciar" as hacerSimulacion

}

user8 --> paginaProyecto : "Selecciona"
user8 --> importarExistente : "Selecciona"
user8 --> datosSimulacion : "Ingresa"
user8 --> hacerSimulacion : "Selecciona"

@enduml