@startuml
title Caso de Uso Project_Dashboard - FISC

left to right direction

actor Usuario as user


rectangle "Project Dashboard" {
    usecase "Borrar Simulación" as borrar
    usecase "Exportar Simulación" as exportar
    usecase "Editar Simulación" as editar
    usecase "Crear Nueva Simulación" as crear
    usecase "Importar Simulación" as importar
    usecase "Ver Reporte" as ver
}

user --> borrar
user --> exportar
user --> editar
user --> crear
user --> importar
user --> ver
@enduml