@startuml

title Caso de Uso Pantalla de carga - FISC

left to right direction

actor Usuario as user6

rectangle "FISC Pantalla de carga" {
  usecase "Cancelar" as pararSimulacion
  usecase "Simulación completada" as esperarSimulacion
}

user6 --> pararSimulacion : "Selecciona"
user6 --> esperarSimulacion : "Espera"

@enduml
