@startuml CRUD_Suscription

title CRUD Suscripción

folder "CRUD Suscripción" {

    actor Egresado

    Egresado --> (Listar Paquetes Servicios)
    (Listar Paquetes Servicios) --> (Listar servicios) : <<include>>
    Egresado --> (Suscripción Paquete Servicio)
    (Suscripción Paquete Servicio) --> (Suscripción servicio) : <<include>>
    Egresado --> (Editar Suscripción Paquetes Servicio)
    (Editar Suscripción Paquetes Servicio) --> (Editar suscripción servicio) : <<include>>
    Egresado --> (Eliminar Suscripción Paquetes Servicio)
    (Eliminar Suscripción Paquetes Servicio) --> (Eliminar suscripción servicio) : <<include>>

}

@enduml