@startuml
skinparam defaultFontName Arial
top to bottom direction

[*] --> CancelaciónSolicitada: Solicitud de cancelación de cuenta

state CancelaciónSolicitada{
  state ComprobarRequisitos <<choice>>
  [*] --> ComprobarRequisitos : Se valida la cuenta a cancelar
  ComprobarRequisitos --> UsuarioEliminado: Los datos se han validado correctamente
  ComprobarRequisitos --> UsuarioBloqueado: La cuenta a cancelar a incumplido los terminos de uso
}
@enduml
