@startuml

class SistemaAsignacionGrados {
    - grados
    - docentes
}

class Grado {
    - nombre
    - codigo
}

class Docente {
    - nombre
    
}

class AsignadorDeGrados {
    - asignarGradosADocentes
    - verificarGradosPendientes
}

SistemaAsignacionGrados  -->  Grado 
SistemaAsignacionGrados  -->  Docente 
SistemaAsignacionGrados  -->  AsignadorDeGrados 

@enduml
 