@startuml

class Grado {
    - nombre
    - id
    - planEstudios
    + elegirAño()
    + asignarAsignaturas()
}

class PlanEstudios {
    - asignaturasPorAño 
    + obtenerAsignaturasPorAño()
}

class Asignatura {
    - nombre
    - idAsignatura
}

class AñoGrado {
    - año
    - asignaturas
    + asignarAsignaturas()
}

class Semestre {
    - numero
    - asignaturas
}

Grado --> PlanEstudios : tiene
Grado --> AñoGrado : incluye
AñoGrado  -->  Asignatura : incluye
AñoGrado --> Semestre : divide

@enduml
