[*] --> RegistrandoDatos: se crea administrador

RegistrandoDatos-->UsuarioAdministrador :se han registrado los datos


state UsuarioAdministrador{
Activo-->GestionandoEstadísticas
[*]-->Activo: necesita gestionar Alumni
Activo-->gestionandoServicio 
Activo-->gestionandoPaquetes 
Activo --> Inactivo
Inactivo --> Activo
}


@enduml
