@startuml
[*] --> UsuarioAdministrador: se crea administrador



state UsuarioAdministrador{
Activo-->GestionandoEstadísticas
[*]-->Activo: necesita gestionar Alumni
Activo-->gestionandoServicio 
Activo-->gestionandoPaquetes 
Activo --> Inactivo
Inactivo --> Activo
}


@enduml