@startuml Contexto
title Contexto Administrador

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
INICIAR_SESIÓN --> INICIO : Iniciar Sesión

INICIO -> ADMINISTRADORES
INICIO <- ADMINISTRADORES

ADMINISTRADORES -> CREAR_ADMINISTRADOR
ADMINISTRADORES <- CREAR_ADMINISTRADOR
ADMINISTRADORES -> EDITAR_ADMINISTRADOR
ADMINISTRADORES <- EDITAR_ADMINISTRADOR
ADMINISTRADORES -> ELIMINAR_ADMINISTRADOR
ADMINISTRADORES <- ELIMINAR_ADMINISTRADOR
ADMINISTRADORES -> LISTAR_ADMINISTRADOR
ADMINISTRADORES <- LISTAR_ADMINISTRADOR
ADMINISTRADORES -> REALIZAR_PETICION
ADMINISTRADORES <- REALIZAR_PETICION

INICIO --> [*] : Cerar Sesión
ADMINISTRADORES --> [*] : Cerar Sesión


@enduml