@startuml Contexto
title Contexto Administrador

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
INICIAR_SESIÓN --> INICIO : Iniciar Sesión

INICIO -> GESTIÓN_EGRESADOS
INICIO <- GESTIÓN_EGRESADOS
INICIO -> ADMINISTRADORES
INICIO <- ADMINISTRADORES
INICIO -> GESTIÓN_SERVICIOS
INICIO <- GESTIÓN_SERVICIOS
INICIO -> GESTIÓN_PAQUETES
INICIO <- GESTIÓN_PAQUETES
INICIO -> CONFIGURACIÓN
INICIO <- CONFIGURACIÓN
INICIO -> EXPLORAR_SERVICIOS
INICIO <- EXPLORAR_SERVICIOS
INICIO -> SERVICIOS
INICIO <- SERVICIOS

INICIO --> [*] : Cerrar Sesión
SERVICIOS --> [*] : Cerrar Sesión
GESTIÓN_EGRESADOS --> [*] : Cerrar Sesión
ADMINISTRADORES --> [*] : Cerrar Sesión
GESTIÓN_SERVICIOS --> [*] : Cerrar Sesión
GESTIÓN_PAQUETES --> [*] : Cerrar Sesión
CONFIGURACIÓN --> [*] : Cerrar Sesión
EXPLORAR_SERVICIOS --> [*] : Cerrar Sesión


@enduml