@startuml

title Caso de Uso Pagina Principal - FISC

left to right direction

actor Usuario as user

rectangle "FISC Pagina Principal" {
    usecase "Exportar Proyecto" as exportar
    usecase "Abrir Proyecto" as abrir
    usecase "Importar Proyecto" as importar
    usecase "Nuevo Proyecto" as nuevo
}

user --> exportar : ""
user --> abrir : ""
user --> importar : ""
user --> nuevo : ""

@enduml
