@startuml Contexto
title Contexto Administrador

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
INICIAR_SESIÓN --> INICIO : Iniciar Sesión

INICIO -> GESTIÓN_PAQUETES
INICIO <- GESTIÓN_PAQUETES

GESTIÓN_PAQUETES -> CREAR_PAQUETE
GESTIÓN_PAQUETES <- CREAR_PAQUETE
GESTIÓN_PAQUETES -> EDITAR_PAQUETE
GESTIÓN_PAQUETES <- EDITAR_PAQUETE
GESTIÓN_PAQUETES -> ELIMINAR_PAQUETE
GESTIÓN_PAQUETES <- ELIMINAR_PAQUETE
GESTIÓN_PAQUETES -> LISTAR_PAQUETE
GESTIÓN_PAQUETES <- LISTAR_PAQUETE
GESTIÓN_PAQUETES -> REALIZAR_PETICIÓN
GESTIÓN_PAQUETES <- REALIZAR_PETICIÓN

INICIO --> [*] : Cerar Sesión
GESTIÓN_PAQUETES --> [*] : Cerar Sesión


@enduml