@startuml AlumniModel

'!theme amiga
skinparam backgroundColor white
skinparam defaultFontName Arial

class ALUMNI 
{
   plataforma
}

class "SERVICIO EXTERNO" {}

class UNIVERSIDAD {}



class EGRESADO 
{
    - ID: 000001
    + Nombre : Pepe
    + Apellido: San Vitores
    - Fecha de Nacimiento 19-6-1999
    - Email: pepe@alumnos.uneatlantico.es
    - ubicacion: Santander
    + Ocupación: desempleado
    -Carnet de Estudiante:123456Z
}

class ADMINISTRADOR
{
    - ID: 000002
    + Nombre : Juanjo
    + Apellido: Gimenez  
    - Fecha de Nacimiento 19-6-1984
    - Email: juanjo@uneatlantico.es
    - Zona de trabajo: Uneatlatico
}

class REQUISITO 
{
    + titulación de UNEAT
}

class ESTADISTICAS 
{
    - información de los egresados
}

class SUSCRIPCIÓN 
{
    - paquetes suscritos:premium
    - servicios suscritos: Instalaciones, Comunicacion,
     Newsletter, Ofertas de trabajo
    - precio total 20 €
}

class PAQUETE
{
    + Nombre: premium
    + Descripción: Ofrece incluye instalaciones y ofertas de empleo
    + servicios incluidos: incluye newsletter y ofertas de empleo
    + precio: 20 €
}

class COMUNICACIÓN 
{
   + Nombre: Comunicación
   + Descripción: Permite comunicarse
    e interactuar con otros usuarios
   +precio: 0 €
   + Email: pepe@alumnos.uneatlantico.es
    -  Chat
    - Seguimiento
}

class INSTALACIONES 
{
    + Nombre: Instalaciones
    + Descripción: Concede acceso a diferentes 
    instalaciones dentro de la universidad
    + precio: 25 €
    + Biblioteca
    + Sala de ordenadores
    + Instalaciones deportivas
}

class NEWSLETTER 
{
    + Nombre:  newsletter
    + Descripción: Tablon de anuncios donde 
    se comparten eventos y noticias
    + Precio 0 €
    + Noticias practicas con inditex
    + Eventos
}

class "OFERTAS DE EMPLEO" 
{
    + Nombre: Ofertas de empleo Amazon
    + Descripción: Informacion referente a
    diversas ofertas de empleo disponibles
    + precio: 5 €
    + Nombre de la empresa
    + Puesto de trabajo
    + Salario
    + Ubicación
}

EGRESADO -up- ALUMNI  : tiene
ALUMNI -- ADMINISTRADOR : tiene
EGRESADO -- SUSCRIPCIÓN : se inscribe
ALUMNI -right- "SERVICIO EXTERNO" : se comunica

EGRESADO -right- REQUISITO : cumple
ALUMNI -right- ESTADISTICAS : genera
ADMINISTRADOR .right. ESTADISTICAS : consulta
SUSCRIPCIÓN -right- PAQUETE : incluye

UNIVERSIDAD -right- ALUMNI : se comunica

ADMINISTRADOR .. PAQUETE

SUSCRIPCIÓN <|-- "COMUNICACIÓN"
SUSCRIPCIÓN <|-- "INSTALACIONES"
SUSCRIPCIÓN <|-- "NEWSLETTER"
SUSCRIPCIÓN <|-- "OFERTAS DE EMPLEO"

@enduml