@startuml

title Caso de Uso Página Proyecto - FISC

left to right direction

actor Usuario as user2

rectangle "FISC Página Proyecto" {
  usecase "Nueva simulación" as nueva
  usecase "Abrir simulación" as abrir
  usecase "Ver reporte" as reportes
}
  user2 --> nueva : ""
  user2 --> abrir : ""
  user2 --> reportes : ""

@enduml