@startuml

state IniciandoSistema{

State accion1 <<choice>> 

[*] --> CompruebaRequisitos

CompruebaRequisitos --> accion1 : ¿Los cumple?

accion1--> [*] :NO

accion1 --> SolicitandoDatosUNEAT : SI

SolicitandoDatosUNEAT --> GeneraEstadísticas

}

GeneraEstadísticas --> SuscribirUsuario : suscribe al usuario

state SistemaFuncional{

State accion <<choice>> 

GeneraEstadísticas --> ApartadoSocial : comunica usuarios con

SuscribirUsuario --> accion : ¿Está suscrito?

accion --> gestionaServicios : SI

accion --> [*] : NO


}
@enduml