@startuml

state Fichar as " "
state NoFichar as " "

[*] --> Fichar : [Inicio de jornada laboral]


state Turno <<choice>>

Fichar -r-> Turno : Fichar

Turno -r-> NoFichar : [Salida de profesor]

NoFichar -l-> Turno : Desfichar

Turno -l-> Fichar : [Entrada de profesor]

Turno -d-> [*] : [Final de jornada laboral]

@enduml
