@startuml

title Diagrama de Objetos del Estado Generando Reporte - Simulación en Aplicación FISC

object "usuario1 : Usuario" as usuario1 {
    nombre = "Jorge"
    id = 1
}

object "proyecto1 : Proyecto" as proyecto1 {
    nombre = "Proyecto X"
}

object "simulación1 : Simulación" as simulación1 {
    tipologíaElemento = "BIDIMENSIONAL"
    material = material1
    agresiónTérmica = agresiónTérmica1
    gráficaReacción = gráfica1
    fechaSimulación = "2023-11-03"
}

object "gráfica1 : Gráfica" as gráfica1 {
    datos = "x, y"
    tipoGráfica = "Curva de Calor"
}

object "log1 : Log" as log1 {
    acciones = ["Login", "Creación Proyecto", "Inicio Simulación"]
    fechaHora = "2023-11-03T10:00:00"
}

object "reporte1 : Reporte" as reporte1 {
    contenido = "Contenido del reporte"
    formato = "PDF"
}

usuario1 - proyecto1 : "realiza >"
proyecto1 -- simulación1 : "contiene >"
simulación1 -- gráfica1 : "genera >"
simulación1 -- reporte1 : "produce >"
log1 -- usuario1: "registra >"
log1 -- proyecto1 : "registra >"

@enduml