@startuml
title Flujo de la Aplicación FISK

start

:Iniciar Aplicación;
:Crear Nuevo Proyecto,\nAbrir Proyecto Existente\no Abrir Simulación Existente;
if (Nuevo Proyecto) then (sí)
    :Configurar Nuevo Proyecto;
elseif (Proyecto Existente) then (no)
    :Seleccionar Proyecto Existente;
else (Simulación Existente)
    --> Revisar y Confirmar Datos;
endif

if (Nuevo Proyecto o Proyecto Existente) then (sí)
    :Seleccionar Tipología;
    :Configurar/Importar Material;
    :Configurar Agresión Térmica;
endif

:Revisar y Confirmar Datos;
if (¿Hay Errores en Tipología?) then (sí)
    --> Seleccionar Tipología;
elseif (¿Errores en Material?) then (sí)
    --> Configurar/Importar Material;
elseif (¿Errores en Agresión Térmica?) then (sí)
    --> Configurar Agresión Térmica;
else (no)
    :Iniciar Simulación;
endif

:Generar Resultados;
:Visualizar Gráficos y Datos;
:Generar Reporte;
:Exportar Datos/Reporte (Opcional);
:Guardar Proyecto;
stop

@enduml
