@startuml
class Trabajador{
   
}
class LectorDeHuellas{
    + Huella
}
class Fichaje{
    + Fecha
    + Hora
}
class Informe{
    + Trabajador
    + Fecha
    + HorasDia
    + HorasSemana
    + HorarioCumplido
}
class Horario{
    + Dia
    + HoraEntrada
    + HoraSalida
}
class Contrato{
    + Tipo
}
class Normas{

}

Trabajador -- Contrato : Tiene
Trabajador .. LectorDeHuellas : Usa
LectorDeHuellas -- Fichaje : Se usa para
Fichaje -- Informe : Se describen en
Informe .. Horario : Verifica que se cumpla
Contrato -- Normas : Establece
Normas-- Horario : Regulan
Normas.. Fichaje : Define
Trabajador -- Informe : Revisa
Trabajador -- Fichaje :Realiza


@enduml
