
@startuml
'https://plantuml.com/sequence-diagram
title Modelo del entorno



object "institucion" as funiber
object "uneatlantico" as universidad
object "secretaria" as secretariaAcademica
object "masias" as profesor



'https://plantuml.com/class-diagram

object "Lampara" as Luz
object "Cuaderno" as Objeto
object "Sombra_de_objeto" as Sombra

Luz : encender()
Luz : apagar()
Objeto : escribir()
Objeto : dibujar()
Sombra : proyectar()
Sombra : generar()

Luz --> Objeto:Ilumina
Objeto --> Sombra:Proyecta
Luz --> Sombra:Genera

@enduml