@startuml

!define RECTANGLE class
!define INTERFACE interface

package "CORE de Gestión Docente" {
    RECTANGLE Login
    RECTANGLE Dashboard {
        RECTANGLE Campus
        RECTANGLE Notas
        RECTANGLE OpcionesGenerales
        RECTANGLE Docentes
    }
    RECTANGLE Permisos
    RECTANGLE Asignaciones
    RECTANGLE Bajas {
        RECTANGLE Temporales
        RECTANGLE Permanentes
    }
    RECTANGLE Notificaciones
    RECTANGLE Configuraciones
    RECTANGLE Migraciones
}

Login --|> Dashboard : Iniciar sesión
Dashboard --|> Campus : Acceder
Dashboard --|> Notas : Acceder
Dashboard --|> OpcionesGenerales : Acceder
Dashboard --|> Docentes : Acceder
Dashboard --|> Permisos : Acceder
Dashboard --|> Asignaciones : Acceder
Dashboard --|> Bajas : Acceder
Dashboard --|> Notificaciones : Acceder
Dashboard --|> Configuraciones : Acceder
Dashboard --|> Migraciones : Acceder

Bajas --|> Temporales : Temporales
Bajas --|> Permanentes : Permanentes

Admin --|> Configuraciones : Administra

note right of Dashboard : Vista Home\nMuestra las aplicaciones\nde uso diario de los docentes

note right of Docentes : Vista general de docentes\nCreación y edición de docentes\nFiltrado y exportación\nVisualización de perfiles\nSeguimiento de docentes

note right of Permisos : Visualización de acciones de usuario

note right of Asignaciones : Asignar y desasignar asignaturas\na docentes

note right of Bajas : Gestionar bajas\nReincorporación de docentes

note right of Notificaciones : Envío de notificaciones\na los docentes

note right of Configuraciones : Configuración de la aplicación

note right of Migraciones : Migración de datos\npara backup

@enduml