@startuml
'https://plantuml.com/sequence-diagram
title Modelo del dominio Core
 
core --> usuario : "usa"
usuario --> asignacion : "permite acceder "
usuario --> baja : "permite acceder a"
usuario --> universidad : "permite acceder a"
usuario --> permiso : "se le asigna"
asignacion --> asignatura : "eleccion"

class ticket

@enduml