@startuml
'https://plantuml.com/sequence-diagram
title Modelo del entorno
profesor --> core : > utiliza
secretariaAcademica --> core: > utiliza
profesor -- ticket: > crea
secretariaAcademica -- ticket: > crea
core -- ticket : > registra\nsus errores en

@enduml