@startuml
'https://plantuml.com/sequence-diagram
title Modelo del dominio Core

usuario --up core : "Es ocupado por"
admin --up core : "Es ocupado por"
developer --up core : "Es ocupado por"
funiber --up usuario : "Los cuales son"
modulo --up admin : "Administra"
modulo --up developer : "Desarrolla"
modulo --up funiber : "Ocupa"
privado --up modulo : "Se divide en"
publico --up modulo : "Se divide en"
login --up publico : "permite acceder a"
dashboard --up publico : "permite acceder a"
docente --up publico : "permite acceder a"
notificacion --up publico : "permite acceder a"
permiso --up privado : "permite acceder a"
asignacion --up privado : "permite acceder a"
bajas --up privado : "permite acceder a"
configuracion --up privado : "permite acceder a"
migracion --up privado : "permite acceder a"

@enduml