@startuml

class Contrato {

}

class Horario {

}

class Trabajadores {

}

class LectorDeHuellas {

}

class Fichaje {

}

class Informe {

}

class EquipoDeControl {

}

Contrato "Establece" -- Horario
Trabajadores "Tiene" --  Contrato
Trabajadores "Usa" -- LectorDeHuellas
LectorDeHuellas "Para" -- Fichaje
Fichaje "Se usa en un" -- Informe
EquipoDeControl "Revisa" -- Informe

@enduml
