@startuml

class Horario {
    - int horas
    - String[] dias
    - String[] bloquesHorarios
    + Horario()
    + asignarHoras()
    + asignarDias()
}

class HorarioGrado {
    - String nombreGrado
    - int anioGrado
    - String[] asignaturasGrado
    + HorarioGrado()
}

class HorarioAula {
    - boolean disponibilidadAula
    - int numeroAulas
    - String nombreDocente
    - int horarioDisponible
    + HorarioAula()
}

class HorarioDocente {
    - String nombreDocente
    - int horarioDisponible
    + HorarioDocente()
}

class AulaReservadaException {
    + AulaReservadaException()
}

Horario <|-- HorarioGrado
Horario <|-- HorarioAula
Horario <|-- HorarioDocente
HorarioAula -- AulaReservadaException : throws >

@enduml
