@startuml AumniClasses

title Diagrama de Clases

'!theme amiga
skinparam backgroundColor white
skinparam defaultFontName Arial

hide empty members

class PLATAFORMA 
{
   Alumni
}

abstract "SERVICIO EXTERNO"

abstract USUARIO 
{
    ID
    Nombre 
    Apellido
    Fecha de Nacimiento
    Email
    Foto de Perfil
}

class EGRESADO 
{
    Ubicacion
    Ocupación
    Carnet de Estudiante
}

class ADMINISTRADOR 
{
}

class REQUISITO 
{
    Titulación de UNEAT
}

class ESTADISTICA 
{
}

class SUSCRIPCIÓN 
{
    Paquetes Suscritos
    Servicios Suscritos
    Precio Total
}

class PAQUETE
{
    Nombre
    Descripción
    Servicios incluidos
    Precio
}

abstract SERVICIO 
{
    Nombre 
    Descripción
    precio
    tipo de servicio
}

PLATAFORMA -- USUARIO : tiene
PLATAFORMA -left ESTADISTICA : genera
PLATAFORMA -right- "SERVICIO EXTERNO" : se comunica
SERVICIO .up..|> "SERVICIO EXTERNO"
SUSCRIPCIÓN -up- PLATAFORMA : tiene
SUSCRIPCIÓN -- SERVICIO : incluye
EGRESADO -- REQUISITO : cumple
SUSCRIPCIÓN -- PAQUETE : incluye
PAQUETE - SERVICIO : incluye
USUARIO <|-- EGRESADO
USUARIO <|-- ADMINISTRADOR
ADMINISTRADOR -up- PLATAFORMA : administra

@enduml
