@startuml Platform_Register

title Registro en plataforma

actor Egresado

Egresado --> (Registro en plataforma)
(Registro en plataforma) --> (Suscipción a servicio) : <<include>>
(Registro en plataforma) --> (Suscipción a paquete de servicios) : <<include>>

@enduml