@startuml registro_en_alumni

title Registro en Alumni
skinparam defaultFontName Arial

actor Egresado

Egresado -> (Alumni): se registra

(Alumni) -> (Alumni): valida datos
(Alumni) -up-> (Alumni): envia correo de confirmacion
(Alumni) -up-> (Base de datos): guarda datos
(Alumni) -down-> (Suscripción): genera suscripción

(Base de datos) -> (Base de datos uneat) : se relaciona

(Suscripción) -> (Comunicación): añade el servicio
(Suscripción) -down-> (Newsletter): añade el servicio 
@enduml