@startuml Contexto
title Contexto Administrador

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
INICIAR_SESIÓN --> INICIO : Iniciar Sesión

INICIO -> CONSULTAR_ESTADÍSTICAS
INICIO <- CONSULTAR_ESTADÍSTICAS
INICIO -> REALIZAR_PETICIÓN
INICIO <- REALIZAR_PETICIÓN

INICIO --> [*] : Cerrar Sesión

@enduml