@startuml Contexto
title Contexto Administrador

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
INICIAR_SESIÓN --> INICIO : Iniciar Sesión

INICIO -> GESTIÓN_EGRESADOS
INICIO <- GESTIÓN_EGRESADOS

GESTIÓN_EGRESADOS -> CREAR_EGRESADO
GESTIÓN_EGRESADOS <- CREAR_EGRESADO
GESTIÓN_EGRESADOS -> EDITAR_EGRESADO
GESTIÓN_EGRESADOS <- EDITAR_EGRESADO
GESTIÓN_EGRESADOS -> ELIMINAR_EGRESADO
GESTIÓN_EGRESADOS <- ELIMINAR_EGRESADO
GESTIÓN_EGRESADOS -> LISTAR_EGRESADO
GESTIÓN_EGRESADOS <- LISTAR_EGRESADO
GESTIÓN_EGRESADOS -> REALIZAR_PETICIÓN
GESTIÓN_EGRESADOS <- REALIZAR_PETICIÓN

INICIO --> [*] : Cerrar Sesión
GESTIÓN_EGRESADOS --> [*] : Cerrar Sesión


@enduml