@startuml
title Flujo de la Aplicación FISK

start

:Iniciar Aplicación;
:Crear Nuevo Proyecto\no Abrir Existente;
if (Nuevo Proyecto) then (sí)
    :Configurar Nuevo Proyecto;
else (no)
    :Seleccionar Proyecto Existente;
endif

:Seleccionar Tipología;
:Configurar Material;
:Configurar Agresión Térmica;
:Revisar y Confirmar Datos;
:Iniciar Simulación;

if (¿Hay Errores?) then (sí)
    :Mostrar Errores;
    :Corregir Datos;
    -> Revisar y Confirmar Datos;
else (no)
    :Generar Resultados;
endif

:Visualizar Gráficos y Datos;
:Generar Reporte;
:Exportar Datos/Reporte;
:Guardar Proyecto;
stop

@enduml
