@startuml
skin rose
title Diagrama de Contexto (Filtrado de Tickets)

[*] --> Inicial

Inicial -d-> DASHBOARD_ABIERTO : login

DASHBOARD_ABIERTO --> FILTRAR_TICKETS

FILTRAR_TICKETS <-- FILTRAR_POR_PALABRA_CLAVE
FILTRAR_TICKETS <-- FILTRAR_POR_ESTADO
FILTRAR_TICKETS <-- FILTRAR_POR_PRIORIDAD
FILTRAR_TICKETS <-- FILTRAR_POR_FECHA

FILTRAR_TICKETS --> FILTRAR_POR_PALABRA_CLAVE
FILTRAR_TICKETS --> FILTRAR_POR_ESTADO
FILTRAR_TICKETS --> FILTRAR_POR_PRIORIDAD
FILTRAR_TICKETS --> FILTRAR_POR_FECHA

DASHBOARD_ABIERTO --> [*] : logout
FILTRAR_TICKETS --> [*] : logout
@enduml
