@startuml Diagrama de Contexto (Administrador)

skin rose
skinparam note{
  BackgroundColor white
}
title Diagrama de Contexto (Administrador)

[*] -->  Inicial

Inicial -d-> DASHBOARD_ABIERTO
note on link: login

DASHBOARD_ABIERTO --> LISTA_TICKETS
note on link: filtrarTickets

LISTA_TICKETS --> TICKET
TICKET --> LISTA_TICKETS
note on link: verTicket

VER_USUARIOS <-- AÑADIR_USUARIO
VER_USUARIOS <-- EDITAR_USUARIO
VER_USUARIOS <-- BAJAS_USUARIOS

VER_USUARIOS --> AÑADIR_USUARIO : añadirUsuario
VER_USUARIOS --> EDITAR_USUARIO : editarUsuario 
VER_USUARIOS --> BAJAS_USUARIOS : bajaDeUsuario

DASHBOARD_ABIERTO --> INFORME : verInforme
DASHBOARD_ABIERTO <-- INFORME

INFORME --> DIARIO
INFORME --> SEMANAL
INFORME --> MENSUAL

INFORME <-- DIARIO
INFORME <-- SEMANAL
INFORME <-- MENSUAL


DASHBOARD_ABIERTO --> [*] : logout
VER_USUARIOS --> [*] : logout
INFORME --> [*] : logout


@enduml