@startuml Diagrama_de_Objetos-Servicio_Externo
title Interacción con el Servicio de Instalaciones

skinparam backgroundColor white
skinparam defaultFontName Arial
hide circle

class "INSTALACIONES : SERVICIO EXTERNO"  
{
    Nombre: "Instalaciones +"
    Precio: "13€"
    Descripción: "Con este servicio podrás\nalquilar instalaciones como las canchas \nde fútbol"
    Url: "https://ejemplo.com"
}


class "BEN : EGRESADO"
{
    
}

"INSTALACIONES : SERVICIO EXTERNO" -left- "ALUMNI"
note left: La plataforma se comunica \ncon el servicio y pasa todos \nlos datos necesarios del egresado \npara iniciar sesión del egresado \nen el servicio
"ALUMNI" -- "BEN : EGRESADO" : comunica
note right: Es el que usa el servicio\npara reservar la instalación. \n\nSe dan por echo todos los \ndatos que debería tener un \negresado  
@enduml

