@startuml
skinparam defaultFontName Arial
top to bottom direction

[*] --> ActualizarDatosCuenta: Datos a actualizar
state ComprobarDatos <<choice>>
ActualizarDatosCuenta --> ComprobarDatos: Se comprueban los cambios
ComprobarDatos --> DatosActualizados
ComprobarDatos --> DatosNoActualizados
@enduml
