@startuml Contexto
title Contexto Administrador

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
INICIAR_SESIÓN --> INICIO : Iniciar Sesión

INICIO -> GESTIÓN_SERVICIOS
INICIO <- GESTIÓN_SERVICIOS

GESTIÓN_SERVICIOS -> CREAR_SERVICIO
GESTIÓN_SERVICIOS <- CREAR_SERVICIO
GESTIÓN_SERVICIOS -> EDITAR_SERVICIO
GESTIÓN_SERVICIOS <- EDITAR_SERVICIO
GESTIÓN_SERVICIOS -> ELIMINAR_SERVICIO
GESTIÓN_SERVICIOS <- ELIMINAR_SERVICIO
GESTIÓN_SERVICIOS -> LISTAR_SERVICIO
GESTIÓN_SERVICIOS <- LISTAR_SERVICIO
GESTIÓN_SERVICIOS -> REALIZAR_PETICIÓN
GESTIÓN_SERVICIOS <- REALIZAR_PETICIÓN

INICIO --> [*] : Cerrar Sesión
GESTIÓN_SERVICIOS --> [*] : Cerrar Sesión


@enduml