@startuml Contexto
title Contexto Egresado

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
[*] --> REGISTRAR_EGRESADO
INICIAR_SESIÓN --> INICIO : Iniciar Sesión
REGISTRAR_EGRESADO --> INICIO : Registrar Egresado


INICIO -> CONFIGURACIÓN
INICIO <- CONFIGURACIÓN

CONFIGURACIÓN -> CANCELACIÓN_CUENTA
CONFIGURACIÓN <- CANCELACIÓN_CUENTA
CONFIGURACIÓN -> LISTAR_DATOS_USUARIO
CONFIGURACIÓN <- LISTAR_DATOS_USUARIO
CONFIGURACIÓN -> EDITAR_DATOS_USUARIO
CONFIGURACIÓN <- EDITAR_DATOS_USUARIO
CONFIGURACIÓN -> REALIZAR_PETICIÓN
CONFIGURACIÓN <- REALIZAR_PETICIÓN

CONFIGURACIÓN -> [*] : Cerrar Sesión
INICIO --> [*] : Cerar Sesión

@enduml