[*] --> Usuario : se crea usuario
State accion <<choice>>
Usuario --> accion
accion --> UsuarioEgresado : es egresado
accion --> UsuarioAdministrador : es administador
state UsuarioEgresado{
State accion1 <<choice>>
[*]-->accion1
accion1 --> [*] : no cumple requisito
accion1 --> Egresado : cumple requisito
Egresado --> [*] : se elimina registro
Egresado --> Suscrito : se inscribe
Suscrito--> Egresado: se desinscribe
}
state UsuarioAdministrador{
[*]--> mirandoEstadísticas : llegan nuevos datos
[*]-->gestionandoServico : se crea nuevo servicio
[*]-->gestionandoPaquetes : se crea nuevo paquete
}


@enduml
