@startuml

class SistemaAsignacionAulas {
    - aulas
    - aulasAsignadas
}

class Aula {
    - nombre
    - disponible
}

class AsignadorDeAulas {
    + asignarAulas
    + verificarDisponibilidad
}

SistemaAsignacionAulas  -->  Aula 
SistemaAsignacionAulas  --> AsignadorDeAulas 

@enduml
