@startuml

left to right direction

actor "Jefe de Proyecto" as JefeProyecto
actor Administrador as Admin
actor Usuario as Usuario
actor Desarrollador as Dev

rectangle SistemaTicket{
    Dev -l-> Usuario
    Dev -- (Buscar Ticket)
    Dev -- (Comentar Ticket)
    Dev -- (Solventar Ticket)
    Usuario -l- (Crear Ticket)
    Usuario -- (Ver Ticket)
    JefeProyecto -l-> Usuario
    JefeProyecto -- (Asignar Ticket)
    JefeProyecto -- (Buscar Ticket)
    (Buscar Ticket) .. (Filtrar Fecha) : <<extends>>
    (Buscar Ticket) .. (Filtrar Prioridad) : <<extends>>
    (Buscar Ticket) .. (Filtrar Responsable) : <<extends>>
    (Buscar Ticket) .. (Filtrar Estado) : <<extends>>
    (Buscar Ticket) .. (Filtrar Proyecto) : <<extends>>
    Admin -l-> Usuario
    Admin -l-> JefeProyecto
    Admin -- (Consultar Historial)
    (Consultar Historial) .. (Exportar Informe) : <<extends>>
    Admin -- (Cerrar Ticket)
}

@enduml