@startuml CDU GestionTicket

actor Usuario as usuario
actor Administrador as admin
actor Developer as developer

rectangle Sistema {
  admin -- (Dashboard) : Acceder
  admin -- (developer) : Asignar
  admin -- (Ticket) : Visualizar
  admin -- (Notificacion) : Enviar
  admin -- (Rol) : Gestionar
  admin -- (Asignacion) : Gestionar
  admin -- (Bajas) : Gestionar
  admin -- (Configuracion) : Gestionar
  usuario -- (Ticket) : Crear
  usuario --  (Dashboard) : Acceder
  developer -- (Ticket) : Resuelve
  developer -- (Ticket) : Filtrar
  }
@enduml