@startuml Contexto
title Contexto Egresado

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
[*] --> REGISTRAR_EGRESADO
INICIAR_SESIÓN --> INICIO : Iniciar Sesión
REGISTRAR_EGRESADO --> INICIO : Registrar Egresado

INICIO -> LISTAR_SERVICIOS_PAQUETES
INICIO <- LISTAR_SERVICIOS_PAQUETES
INICIO -> CANCELAR_SERVICIO_PAQUETE
INICIO <- CANCELAR_SERVICIO_PAQUETE
INICIO -> REALIZAR_PETICIÓN
INICIO <- REALIZAR_PETICIÓN

INICIO --> [*] : Cerrar Sesión

@enduml