@startuml

class TimeGuardian {
    + iniciarSistema()
    + gestionarAulas()
    + gestionarGrados()
    + gestionarDocentes()
}

package "Gestión de Aulas" {
    class GestionAulas {
        - aulas
        + iniciarRecuentoAulas()
        + verificarDisponibilidad()
        + asignarAulas()
    }

    class Aula {
        - numero
        - tipo
        - disponible
        - capacidad
        + verificarDisponibilidad()
    }

    class AulasOrdenadores {
        - numeroOrdenadores
    }

    class AulasNormales {
    }

    class ConflictoAula {
        - detalles
        + notificarConflicto()
    }

    GestionAulas --> Aula : gestiona
    Aula <|-- AulasOrdenadores
    Aula <|-- AulasNormales
    GestionAulas --> ConflictoAula : verifica
}

package "Gestión de Grados" {
    class Grado {
        - nombre
        - id
        - planEstudios
        + elegirAño()
        + asignarAsignaturas()
    }

    class PlanEstudios {
        - asignaturasPorAño
        + obtenerAsignaturasPorAño()
    }

    class Asignatura {
        - nombre
        - idAsignatura
    }

    class AñoGrado {
        - año
        - asignaturas
        + asignarAsignaturas()
    }

    class Semestre {
        - numero
        - asignaturas
    }

    Grado --> PlanEstudios : tiene
    Grado --> AñoGrado : incluye
    AñoGrado  -->  Asignatura : incluye
    AñoGrado --> Semestre : divide
}

package "Gestión de Docentes" {
    class GestorDocentes {
        + asignarHorarios()
        + gestionarInformacionDocente()
    }

    class Docente {
        + revisarAsignaturas()
        + consultarHorario()
    }

    GestorDocentes --> Docente : gestiona
}

TimeGuardian --> "Gestión de Aulas" : gestiona
TimeGuardian --> "Gestión de Grados" : gestiona
TimeGuardian --> "Gestión de Docentes" : gestiona

@enduml
