@startuml Contexto
title Contexto Administrador

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INITIAL 

INITIAL --> Alumni
note on link 
Iniciar Sesión
end note
Alumni --> [*]
note on link
Cerrar Sesión
end note

state Alumni as "ALUMNI" {
    [*] --> DASHBOARD
    note on link
    consultar Estadísticas
    Realizar Petición
    end note

    DASHBOARD --> GESTIÓN_EGRESADOS
    note on link 
    Listar Egresado
    Realizar Petición
    end note  
    DASHBOARD <-- GESTIÓN_EGRESADOS
    note on link 
    Consultar Estadisticas
    Realizar Petición
    end note  
    DASHBOARD --> GESTIÓN_ADMINISTRADORES
    note on link 
    Listar Administrador
    Realizar Petición
    end note  
    DASHBOARD <-- GESTIÓN_ADMINISTRADORES
    note on link 
    Consultar Estadisticas
    Realizar Petición
    end note
    DASHBOARD --> GESTIÓN_SERVICIOS
    note on link 
    Listar Servicio
    Realizar Petición
    end note  
    DASHBOARD <-- GESTIÓN_SERVICIOS
    note on link 
    Consultar Estadisticas
    Realizar Petición
    end note
    DASHBOARD --> GESTIÓN_PAQUETES
    note on link 
    Listar Paquetes
    Realizar Petición
    end note  
    DASHBOARD <-- GESTIÓN_PAQUETES
    note on link 
    Consultar Estadisticas
    Realizar Petición
    end note

    GESTIÓN_EGRESADOS --> GESTIÓN_EGRESADOS
    note on link 
    Listar Egresado
    Crear Egresado
    Editar Egresado
    Eliminar Egresado
    end note
    GESTIÓN_ADMINISTRADORES --> GESTIÓN_ADMINISTRADORES
    note on link 
    Listar Administrador
    Crear Administrador
    Editar Administrador
    Eliminar Administrador
    end note
    GESTIÓN_SERVICIOS --> GESTIÓN_SERVICIOS
    note on link 
    Listar Servicio
    Crear Servicio
    Editar Servicio
    Eliminar Servicio
    end note
    GESTIÓN_PAQUETES --> GESTIÓN_PAQUETES
    note on link 
    Listar Paquetes
    Crear Paquetes
    Editar Paquetes
    Eliminar Paquetes
    end note
    
}

@enduml