@startuml

title Diagrama de Objetos Ticket

object "Cliente" as usuario
object "Error" as ticket
object "Modulo" as error
object "Prioridad" as etiqueta
object "Fecha" as fecha
object "Proyecto" as proyecto
object "Pendiente" as estado
object "Desarrolador" as responsable
object "Registro" as historial
object "Informe" as informe

usuario -- ticket: > reporta
ticket *-- error: > de
ticket *-- etiqueta: > con
ticket *-- fecha: > con
ticket *-- estado: > pasa a
ticket *-- responsable: > tiene
ticket *-- historial: > genera
ticket .. proyecto: > tiene

historial -d- informe : > permite generar

@enduml