@startuml Modelo del dominio Ticket
'https://plantuml.com/sequence-diagram
title Modelo del dominio Ticket

class estado
class etiqueta
class fecha
class responsable
class rol 
class informe 
class historial
class proyecto 

usuario -- ticket
usuario *-- rol
ticket *-- etiqueta
ticket .. proyecto
ticket *-- estado
ticket *-- responsable
ticket *-- fecha
ticket *-- historial

historial -d- informe : > permite generar

@enduml