@startuml

title Listar Egresados

skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #green
    linetype polyline
}

hide empty description

state startState as "INITIAL"

startState --> ListarEgresados
note on link
    <b>Administrador Solicita</b>
    * Listar Egresados en Alumni
end note

state ListarEgresados {
    state 2 as " "
    [*] --> [*] 
    note on link
        <b>Sistema Muestra</b>
        * Egresados en Alumni
    end note

    [*] -[#red]-> 2
    note on link
        Error al listar Egresados en Alumni
    end note

    2 -[#red]-> [*]
    note on link
        <b>Sistema Muestra</b>
        * Error al listar Egresados en Alumni
    end note


}

@enduml