@startuml Estructura

title Estructura de los Casos de Uso (Administrador)

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

left to right direction

actor Administrador

Administrador --> (Consultar Estadísticas)

folder "Manejo de Usuario" as cuentas {
    Administrador --> (Actualización de Datos del Usuario)
    Administrador --> (Listar Datos del Usuario)
}

folder "Ingreso a Plataforma" as ingreso {
    Administrador --> (Iniciar Sesión)
    Administrador --> (Cerrar Sesión)
}

folder "CRD Suscripciones" as CRDSuscripciones {
    Administrador --> (Listar Servicios / Paquetes de Servicios)
}

folder "CRUD Servicios" as CRUDServicios {
    Administrador --> (Crear Servicio)
    Administrador --> (Listar Servicios)
    Administrador --> (Editar Servicio)
    Administrador --> (Eliminar Servicio)
}

folder "CRUD Egresados" as CRUDEgresados {
    Administrador --> (Crear Egresado)
    Administrador --> (Listar Egresado)
    Administrador --> (Editar Egresado)
    Administrador --> (Eliminar Egresado)
}

folder "CRUD Paquetes" as CRUDPaquetes {
    Administrador --> (Crear Paquete)
    Administrador --> (Listar Paquete)
    Administrador --> (Editar Paquete)
    Administrador --> (Eliminar Paquete)
}

folder "CRUD Administradores" as CRUDAdministradores {
    Administrador --> (Crear Administrador)
    Administrador --> (Listar Administrador)
    Administrador --> (Editar Administrador)
    Administrador --> (Eliminar Administrador)
}

Administrador --> (Realizar Petición)

@enduml