@startuml
[*] --> InicioHorariosDocente

InicioHorariosDocente --> RevisarAsignaturas : Revisar asignaturas del docente
RevisarAsignaturas --> VerificarDisponibilidadHoraria : Asignaturas verificadas

state VerificarDisponibilidadHoraria {
    [*] --> RevisarHorarioDocente
    RevisarHorarioDocente --> HorarioLibre : Horario disponible
    HorarioLibre --> VerificarDisponibilidadHoraria 
}

VerificarDisponibilidadHoraria --> HorarioDocenteCompleto 
HorarioDocenteCompleto --> [*]

@enduml