@startuml
start
:Se suscribe a paquete;
if (¿Es de pago?) then (si)
:Paga;
else (no)
:No paga;
endif
:Se suscribe a servicio;
if (¿Quiere desuscribirse a un servicio?) then (si)
:Ya no está suscrito al servicio;
stop
else (no)
stop
@enduml