@startuml

title Caso de Uso Inicio - FISC

left to right direction

actor Usuario as user
actor Usuario_no_registrado as user1

rectangle "FISC Inicio" {
    usecase "Login" as login
    usecase "Registrarse" as registro
}

user --> login : ""
user1 --> registro : ""

@enduml
