@startuml

title Caso de Uso Simulando - FISC

left to right direction

actor Usuario as user
actor Tiempo as time

rectangle "FISC Simulando" {
    usecase "Verificar Estado de Simulación" as verificarEstado
    usecase "Cancelar Simulación" as cancelarSimulacion
}

user --> cancelarSimulacion : ""
time --> verificarEstado : ""

@enduml
