@startuml

title Caso de Uso Pagina Proyecto - FISC

left to right direction

actor Usuario as user

rectangle "FISC Pagina Proyecto" {
    usecase "Abrir Simulacion" as abrirSimulacion
    usecase "Nueva Simulacion" as nuevaSimulacion
    usecase "Ver Reporte" as verReporte
}

user --> abrirSimulacion : ""
user --> nuevaSimulacion : ""
user --> verReporte : ""

@enduml
