@startuml

title Caso de Uso Nuevo Proyecto - FISC

left to right direction

actor Usuario as user4

rectangle "FISC Nuevo Proyecto" {
  usecase "Volver" as todosProyectos
  usecase "Nombre" as crearNombre
  usecase "Descripción" as crearDescripcion
  usecase "Aceptar" as ok

}

user4 --> todosProyectos : "Selecciona"
user4 --> crearNombre : "Ingresa"
user4 --> crearDescripcion : "Ingresa"
user4 --> ok : "Selecciona"

@enduml