@startuml

title Caso de Uso Página Principal - FISC

left to right direction

actor Usuario as user

rectangle "FISC Página Principal" {
    
    usecase "Importar Proyecto" as importar
    usecase "Abrir Proyecto" as abrir
    usecase "Crear Proyecto" as nuevo
    usecase "Exportar Proyecto" as exportar
}

user --> importar : ""
user --> abrir : ""
user --> nuevo : ""
user --> exportar : ""

@enduml