@startuml

title Caso de Uso - Pantalla Inicio FISC

left to right direction

actor Usuario as user

rectangle "FISC" {
    usecase "Iniciar Sesión con Usuario y Contraseña" as login
    usecase "Registrarse" as registro
    usecase "Recuperar Contraseña" as recuperar
    usecase "Recordar Usuario" as recordar
}

user --> login : "Accede a"
user --> registro : "Accede a"
user --> recuperar : "Accede a"
user --> recordar : "Accede a"

@enduml

