@startuml
title Caso de Uso LOG - FISC

left to right direction

actor Usuario as user


rectangle "Log acceso cualquier pantalla" {
    usecase "Abrir Log" as log
    usecase "Exportar Log" as exlog
}

user --> log
user --> exlog
@enduml