@startuml

title Caso de Uso Pagina de Proyectos - FISC

left to right direction

actor Usuario as user9

rectangle "FISC Pagina Proyectos" {
  usecase "Importar proyectos" as importar
  usecase "Nuevo proyecto" as newproyect
  usecase "Abrir proyecto" as openproyect
  usecase "Exportar" as exportarproyect

}

  user9 --> importar : "Accede a"
  user9 --> newproyect : "Accede a"
  user9 --> openproyect : "Accede a"
  user9 --> exportarproyect : "Accede a"

@enduml