@startuml

title Caso de Uso FISC - General

left to right direction

actor Usuario as user

rectangle "FISC General" {
    usecase "Abrir Log" as abrirLog
    usecase "Cerrar Sesión" as cerrarSesion
}

user --> abrirLog : ""
user --> cerrarSesion : ""

@enduml
