@startuml

title Caso de Uso - Pantalla Carga FISC

left to right direction

actor Usuario as user

rectangle "Pantalla de Carga" {
    usecase "Cargar Parámetros" as loadParams
}

rectangle "FISC" {
    usecase "Carga datos actuales" as carga
    usecase "Correcta conexión a FISC" as conexión
    usecase "Detección de errores" as errores
}

user --> loadParams : "Visualiza"
loadParams --> carga : realiza
loadParams --> conexión : comprueba
loadParams --> errores : revisa

@enduml