@startuml
skinparam noteBackgroundColor #f5f5f5
skinparam noteBorderColor #c90000
skinparam arrowColor #218c00
skinparam stateBackgroundColor #faf4b4
skinparam stateBorderColor #c90000
skinparam linetype polyline
skinparam arrowThickness 1

[*] --> Inicio

Inicio -d-> FISC 
note on link
  Login
end note
Inicio -d-> Inicio
note on link
  Registrar Usuario
end note

State FISC {
[*] --> PáginaPrincipal 

PáginaPrincipal -d-> PáginaProyecto
note on link
  Abrir Proyecto 
  Importar Proyecto
  Nuevo Proyecto 
end note 
PáginaPrincipal -d-> PáginaPrincipal
note on link
  Exportar Proyecto
end note 

PáginaProyecto -d-> ConfiguraciónDeSimulación
note on link
  Abrir Simulación
  Nueva Simulación
end note 
PáginaProyecto ---> Reporte
note on link
  Ver Reporte
end note 

ConfiguraciónDeSimulación -d-> Simulando
note on link
  Iniciar Simulación
end note 
ConfiguraciónDeSimulación -d-> ConfiguraciónDeSimulación
note on link
  Importar Simulación
end note  

Simulando ---> ConfiguraciónDeSimulación
note on link
  Cancelar Simulación
end note 
Simulando ---> Simulando
note on link
  Verificar Estado de Simulación
end note 
Simulando ---> Reporte
note on link
  Verificar Estado de Simulación
end note 

Reporte -d-> Reporte
note on link
  Exportar Reporte  
  Imprimir Reporte
end note 
Reporte -d-> PáginaProyecto
note on link
  Guardar
end note 
Reporte -d-> ConfiguraciónDeSimulación
note on link
  Editar Simulación
end note 
}

Log ---> Log
note on link
  Imprimir
end note 
FISC -d-> Log
note on link
  Abrir Log
end note 
FISC --> [*]
note on link
  Log Out
end note 

@enduml