@startuml Estructura

title Estructura de los Casos de Uso

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

left to right direction

actor Egresado
actor Administrador
actor Tiempo

Tiempo --> (Eliminar Suscripción a Servicio / Paquete de Servicios)

Administrador --> (Consultar Estadísticas)

folder "Manejo de Usuario" as cuentas {
    Egresado --> (Actualización de Datos del Usuario)
    Egresado --> (Cancelación de Cuenta)
    Egresado --> (Listar Datos del Usuario)
    Administrador --> (Actualización de Datos del Usuario)
    Administrador --> (Listar Datos del Usuario)
}

folder "Ingreso a Plataforma" as ingreso {
    Egresado --> (Registro en Plataforma)
    Egresado --> (Iniciar Sesión)
    Administrador --> (Iniciar Sesión)
    Egresado --> (Cerrar Sesión)
    Administrador --> (Cerrar Sesión)
}

folder "CRD Suscripciones" as CRDSuscripciones {
    Egresado --> (Suscripción a Servicio / Paquete de Servicios)
    Egresado --> (Cancelación de Suscripción a Servicio / Paquete de Servicios)
    Egresado --> (Listar Servicios / Paquetes de Servicios)
    Administrador --> (Listar Servicios / Paquetes de Servicios)
}

folder "CRUD Servicios" as CRUDServicios {
    Administrador --> (Crear Servicio)
    Administrador --> (Listar Servicios)
    Administrador --> (Editar Servicio)
    Administrador --> (Eliminar Servicio)
}

folder "CRUD Egresados" as CRUDEgresados {
    Administrador --> (Crear Egresado)
    Administrador --> (Listar Egresado)
    Administrador --> (Editar Egresado)
    Administrador --> (Eliminar Egresado)
}

folder "CRUD Paquetes" as CRUDPaquetes {
    Administrador --> (Crear Paquete)
    Administrador --> (Listar Paquete)
    Administrador --> (Editar Paquete)
    Administrador --> (Eliminar Paquete)
}

folder "CRUD Administradores" as CRUDAdministradores {
    Administrador --> (Crear Administrador)
    Administrador --> (Listar Administrador)
    Administrador --> (Editar Administrador)
    Administrador --> (Eliminar Administrador)
}

Administrador --> (Realizar Petición)
Egresado --> (Realizar Petición)

'(Consultar Estadísticas) --> (Realizar Petición) : <<include>>
'(Eliminar Egresado) --> (Cancelación de Cuenta) : <<include>>
'(Cancelación de Cuenta) --> (Cancelación de Suscripción a Servicio / Paquete de Servicios) : <<include>>
'(Eliminar Paquete) --> (Listar Servicios) : <<include>>
'(Eliminar Paquete) --> (Cancelación de Suscripción a Servicio / Paquete de Servicios) : <<include>>
'(Editar Paquete) --> (Listar Servicios) : <<include>>
'(Crear Paquete) --> (Listar Servicios) : <<include>>
'(Eliminar Servicio) --> (Cancelación de Suscripción a Servicio / Paquete de Servicios) : <<include>>

@enduml