@startuml

start

:Leer huella;
if (Registrada?) then (Sí)
  :Obtener trabajador;
  :Obtener fecha y hora;
  :Registrar fichaje;
  while (Trabajando?) is (Sí)
    :Contabilizar horas;
  endwhile
  if (Fuera de horario) then (Sí) 
    :Registrar salida;
  else (No)
    :Esperar fichaje;
  endif
  if (Final de semana?) then (Sí)
    :Generar informe;
  endif
else (No)
  :Error "Huella no registrada";
endif

stop

@enduml
