@startuml

skin rose

Usuario -up-|> Trabajador
Administrador -up-|> Usuario

Trabajador --> (Escanea Lector de Huella / Crear registro)

Usuario --> (Leer fichaje diario)
Usuario --> (Leer informe dia)
Usuario --> (Leer informe semana)
Usuario --> (Leer informe mes)

Administrador --> (Leer fichaje diario)

Administrador --> (Leer informe)

Administrador --> (Crear Usuario)
Administrador --> (Leer Usuario)
Administrador --> (Actualizar Usuario)
Administrador --> (Eliminar Usuario)

@enduml
