@startuml

skin rose
left to right direction

Usuario -up-|> Trabajador
Administrador -up-|> Usuario

Trabajador --> (Crear registro)

Usuario --> (Ver fichaje diario)
Usuario --> (Ver informe)

Administrador --> (Ver fichaje diario)
Administrador --> (Editar fichaje diario)

Administrador --> (Ver informe)

Administrador --> (Crear Usuarios)
Administrador --> (Ver Usuarios)
Administrador --> (Editar Usuarios)
Administrador --> (Eliminar Usuarios)

@enduml
