@startuml Diagrama de CDU

skin rose
left to right direction
title Casos de Uso

Administrador -up-|> Usuario

Usuario --> (verFichajeDiario)
Usuario --> (verInforme)

Administrador --> (verFichajeDiario)
Administrador --> (editarFichajeDiario)

Administrador --> (verInforme)

Administrador --> (crearUsuarios)
Administrador --> (verUsuarios)
Administrador --> (editarUsuarios)
Administrador --> (eliminarUsuarios)

@enduml
