@startuml

skin rose

left to right direction

Usuario -up-|> Trabajador
Administrador -up-|> Trabajador

Trabajador --> (Crear registro)

Administrador --> (Leer fichaje diario)

Administrador --> (Leer informe)


Administrador --> (Crear Usuario)
Administrador --> (Leer Usuario)
Administrador --> (Actualizar Usuario)
Administrador --> (Eliminar Usuario)

Usuario --> (Leer fichaje diario)
Usuario --> (Leer informe dia)
Usuario --> (Leer informe semana)
Usuario --> (Leer informe mes)

@enduml