@startuml Diagrama Contexto

skin rose
title Diagrama de contexto

[*] -->  Inicial

Inicial -d-> DASHBOARD_ABIERTO : login/registrarse

DASHBOARD_ABIERTO --> FICHAJE_ACTUAL
DASHBOARD_ABIERTO --> INFORME

DASHBOARD_ABIERTO <-- FICHAJE_ACTUAL
DASHBOARD_ABIERTO <-- INFORME

INFORME --> DIARIO
INFORME --> SEMANAL
INFORME --> MENSUAL

INFORME <-- DIARIO
INFORME <-- SEMANAL
INFORME <-- MENSUAL

DASHBOARD_ABIERTO --> [*] : logout
FICHAJE_ACTUAL --> [*] : logout
INFORME --> [*] : logout

@enduml