@startuml

[*] -->  Inicial

Inicial -d-> DASHBOARD_ABIERTO : login/registrarse

DASHBOARD_ABIERTO --> REPORTE_ABIERTO: abrirReporte
REPORTE_ABIERTO --> DASHBOARD_ABIERTO
REPORTE_ABIERTO --> INFORME_DIARIO_ABIERTO: abrirInformeDiario
INFORME_DIARIO_ABIERTO --> REPORTE_ABIERTO
REPORTE_ABIERTO --> INFORME_SEMANAL_ABIERTO: abrirInformeSemanal
INFORME_SEMANAL_ABIERTO --> REPORTE_ABIERTO
REPORTE_ABIERTO --> INFORME_MENSUAL_ABIERTO: abrirInformeMensual
INFORME_MENSUAL_ABIERTO --> REPORTE_ABIERTO

INFORME_DIARIO_ABIERTO --> [*] : logout
INFORME_SEMANAL_ABIERTO --> [*] : logout
INFORME_MENSUAL_ABIERTO --> [*] : logout
DASHBOARD_ABIERTO --> [*] : logout

@enduml
