@startuml Diagrama Contexto (administrador)

skin rose
title Diagrama de contexto (admin)

[*] -->  Inicial

Inicial -d-> DASHBOARD_ABIERTO : login

DASHBOARD_ABIERTO --> LISTA_EMPLEADOS

LISTA_EMPLEADOS <-- AÑADIR_USUARIO
LISTA_EMPLEADOS <-- EDITAR_USUARIO
LISTA_EMPLEADOS <-- ELIMINAR_USUARIO
LISTA_EMPLEADOS <-- BAJAS_DOCENTES

LISTA_EMPLEADOS --> AÑADIR_USUARIO
LISTA_EMPLEADOS --> EDITAR_USUARIO
LISTA_EMPLEADOS --> ELIMINAR_USUARIO
LISTA_EMPLEADOS --> BAJAS_DOCENTES


DASHBOARD_ABIERTO --> [*] : logout
LISTA_EMPLEADOS --> [*] : logout


@enduml
