@startuml Diagrama Contexto (administrador)

skin rose
title Diagrama de contexto (admin)

[*] -->  Inicial

Inicial -d-> DASHBOARD_ABIERTO : login

DASHBOARD_ABIERTO --> VER_USUARIOS
DASHBOARD_ABIERTO <-- VER_USUARIOS

VER_USUARIOS <-- AÑADIR_USUARIO
VER_USUARIOS <-- EDITAR_USUARIO
VER_USUARIOS <-- ELIMINAR_USUARIO
VER_USUARIOS <-- BAJAS_DOCENTES

VER_USUARIOS --> AÑADIR_USUARIO
VER_USUARIOS --> EDITAR_USUARIO
VER_USUARIOS --> ELIMINAR_USUARIO
VER_USUARIOS --> BAJAS_DOCENTES

DASHBOARD_ABIERTO --> INFORME
DASHBOARD_ABIERTO <-- INFORME

INFORME --> DIARIO
INFORME --> SEMANAL
INFORME --> MENSUAL

INFORME <-- DIARIO
INFORME <-- SEMANAL
INFORME <-- MENSUAL


DASHBOARD_ABIERTO --> [*] : logout
VER_USUARIOS --> [*] : logout
INFORME --> [*] : logout


@enduml