@startuml AlumniModel

'!theme amiga
skinparam defaultFontName Arial
hide circle

class ALUMNI {}

class USUARIO 
{
    ID
    Nombre 
    Apellido 
    Email 
    ubicacion 
    Fecha de Nacimiento
    Ocupación
}

class "BASE DE DATOS" {}

class "BASE DE DATOS UNEAT" {}

class REQUISITO 
{
    titulación de Uneat
}

class SUSCRIPCIÓN
{
    Nombre 
    Tipo
}

class SERVICIO 
{
    Nombre 
    Descripción 
}

class COMUNICACIÓN 
{
    Email
    Chat
}

class "ALQUILER DE INSTALACIONES" 
{
    Biblioteca
    Sala de ordenadores
    Instalaciones deportivas
}

class NEWSLETTER 
{
    Noticias
    Eventos
}

class "OFERTAS DE EMPLEO" 
{
    Nombre de la empresa
    Puesto de trabajo
    Salario
    Ubicación
}

ALUMNI -- USUARIO : tiene
ALUMNI -- SUSCRIPCIÓN : ofrece
SUSCRIPCIÓN -- SERVICIO : incluye
USUARIO -- REQUISITO : cumple
USUARIO -- "BASE DE DATOS" : se guarda
"BASE DE DATOS" -- "BASE DE DATOS UNEAT" : se relaciona

SERVICIO <|-- "COMUNICACIÓN"
SERVICIO <|-- "ALQUILER DE INSTALACIONES"
SERVICIO <|-- "NEWSLETTER"
SERVICIO <|-- "OFERTAS DE EMPLEO"

@enduml