@startuml Contexto
title Contexto Egresado

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
[*] --> REGISTRAR_EGRESADO
INICIAR_SESIÓN --> INICIO : Iniciar Sesión
REGISTRAR_EGRESADO --> INICIO : Registrar Egresado

INICIO -> EXPLORAR_SERVICIOS
INICIO <- EXPLORAR_SERVICIOS

EXPLORAR_SERVICIOS -> LISTAR_SERVICIOS_PAQUETES
EXPLORAR_SERVICIOS <- LISTAR_SERVICIOS_PAQUETES
EXPLORAR_SERVICIOS -> SUSCRIPCIÓN_SERVICIO_PAQUETE
EXPLORAR_SERVICIOS <- SUSCRIPCIÓN_SERVICIO_PAQUETE
EXPLORAR_SERVICIOS -> REALIZAR_PETICIÓN
EXPLORAR_SERVICIOS <- REALIZAR_PETICIÓN

EXPLORAR_SERVICIOS -> [*] : Cerrar Sesión
INICIO --> [*] : Cerar Sesión

@enduml