@startuml CDU AsignarTicket
skin rose
:Dashboard Abierto;
:Ver Lista de Tickets;
:Validar Prioridad;
partition "Asignar Ticket" {
  start
    :Ver Desarrolladores disponibles;
    :Asignar Responsable;
}
stop
@enduml