@startuml CrearTicket
state DetectarError
state CrearTicket
state DetallarError
state AsignarPrioridad
state EnviarTicket

left to right direction

[*] --> DetectarError
DetectarError -r-> CrearTicket
CrearTicket-r-> DetallarError
DetallarError-r-> AsignarPrioridad
AsignarPrioridad -r-> EnviarTicket
EnviarTicket --> [*]



@enduml
