@startuml

state GuardarHistorial
state GenerarInforme
state ExtraerHistorial
[*] -->GuardarHistorial
GuardarHistorial--> ExtraerHistorial
ExtraerHistorial-->GenerarInforme
GenerarInforme--> [*]
@enduml