@startuml
skin rose
title Caso de Uso: Modificar Ticket 

state DASHBOARD_ABIERTO
state VER_TICKET
state FILTRAR_TICKETS

DASHBOARD_ABIERTO --> FILTRAR_TICKETS
note on link: **El usuario** solicita filtrar por propiedad de ticket
FILTRAR_TICKETS --> VER_TICKET
note on link: **El usuario** solicita ver un ticket
VER_TICKET --> ModificarTicket

state ModificarTicket {

  [*] -[#blue]-> modificarTicket
  note on link: **El usuario** solicita modificar un ticket
  state "Modificar propiedades del ticket" as modificarTicket
  modificarTicket -[#blue]-> confirmarCambios
  state "Confirmar cambios del ticket" as confirmarCambios
  confirmarCambios -[#blue]-> [*]
  note on link: **El usuario** solicita cambiar un ticket
  confirmarCambios -[#red]-> [*]
  note on link: **El usuario** solicita cancelar el cambio
    
}


note left of modificarTicket
  **El sistema** permite modificar: 
  ° Estado
  ° Prioridad
  ° Titulo
  ° Descripción
  ° Responsable
  ° Archivos Adjuntos
end note

note right of modificarTicket
  **El usuario** introduce los datos a modificar
end note

@enduml