@startuml
skin rose
title Caso de Uso: Ver Ticket

state DASHBOARD_ABIERTO
state FILTRAR_TICKET

DASHBOARD_ABIERTO --> FILTRAR_TICKET
FILTRAR_TICKET --> VerTicket

state VerTicket {

  [*] -[#blue]-> seleccionarOpcionVer
  note on link : *El usuario* solicita seleccionar un ticket
  state "Seleccionar opción 'Ver Ticket'" as seleccionarOpcionVer
  seleccionarOpcionVer -[#blue]-> [*]
}

note left of seleccionarOpcionVer
  *El sistema muestra*: 
  ° El ticket seleccionado
end note

@enduml