@startuml

[*] --> NoRegistrado
NoRegistrado--> [*]
NoRegistrado-->Registrado : Registrarse
Registrado-->NoRegistrado : Eliminar registro
Registrado-->Inscrito : Darse alta
Inscrito-->Registrado : Darse baja
Inscrito-->Suscrito : Pago
Suscrito-->Inscrito : Darse baja suscripción

@enduml