@startuml Contexto
title Contexto Egresado

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INITIAL
state 2 as " "
INITIAL --> 2
note on link 
Iniciar Sesión
Registrarse
end note 
2 --> DASHBOARD_ABIERTO
note on link 
Listar Servicios / Paquetes
end note

DASHBOARD_ABIERTO --> EXPLORAR_SERVICIOS_ABIERTO
note on link 
Listar Servicios / Paquetes
end note  
DASHBOARD_ABIERTO <-- EXPLORAR_SERVICIOS_ABIERTO
note on link 
Listar Servicios / Paquetes
end note  
DASHBOARD_ABIERTO --> CONFIGURACIÓN_ABIERTO
note on link 
Listar Datos Usuario
end note  
DASHBOARD_ABIERTO <-- CONFIGURACIÓN_ABIERTO
note on link 
Listar Servicios / Paquetes
end note  
DASHBOARD_ABIERTO --> SERVICIOS_ABIERTO
note on link 
Listar Servicios / Paquetes
Realizar Petición
end note  
DASHBOARD_ABIERTO <-- SERVICIOS_ABIERTO
note on link 
Listar Servicios / Paquetes
end note  

EXPLORAR_SERVICIOS_ABIERTO --> EXPLORAR_SERVICIOS_ABIERTO
note on link 
Realizar Petición
Listar Servicios / Paquetes
end note
CONFIGURACIÓN_ABIERTO --> CONFIGURACIÓN_ABIERTO
note on link 
Listar Datos Usuario
Actualizar Datos Usuario
Cancelar Cuenta
end note
SERVICIOS_ABIERTO --> SERVICIOS_ABIERTO
note on link 
Realizar Petición+
end note

CONFIGURACIÓN_ABIERTO --> [*]
note on link 
Cerrar Sesión
end note 
EXPLORAR_SERVICIOS_ABIERTO --> [*]
note on link 
Cerrar Sesión
end note  
SERVICIOS_ABIERTO --> [*]
note on link 
Cerrar Sesión
end note  
DASHBOARD_ABIERTO --> [*]
note on link 
Cerrar Sesión
end note  

@enduml