@startuml AlumniModel

title Modelo de Dominio

'!theme amiga
skinparam backgroundColor white
skinparam defaultFontName Arial
hide circle

class ALUMNI 
{
   plataforma
}

class "SERVICIO EXTERNO" {}

class UNIVERSIDAD {}

class USUARIO 
{
    ID
    Nombre 
    Apellido
    Fecha de Nacimiento
    Email
}

class EGRESADO 
{
    ubicacion
    Ocupación
    Carnet de Estudiante
}

class ADMINISTRADOR 
{
    Zona de trabajo
}

class REQUISITO 
{
    titulación de UNEAT
}

class ESTADISTICAS 
{
    información de los egresados
}

class SUSCRIPCIÓN 
{
    paquetes suscritos
    servicios suscritos
    precio total
}

class PAQUETE
{
    Nombre
    Descripción
    servicios incluidos
    precio
}

class SERVICIO 
{
    Nombre 
    Descripción
    precio
}

ALUMNI -- USUARIO : tiene
EGRESADO -- SUSCRIPCIÓN : se inscribe
ALUMNI -- "SERVICIO EXTERNO" : se comunica
SUSCRIPCIÓN -- SERVICIO : incluye
EGRESADO -- REQUISITO : cumple
ALUMNI -- ESTADISTICAS : genera
ADMINISTRADOR .. ESTADISTICAS : consulta
SUSCRIPCIÓN -- PAQUETE : incluye
USUARIO <|-- EGRESADO
USUARIO <|-- ADMINISTRADOR
UNIVERSIDAD -right- ALUMNI : se comunica
ADMINISTRADOR -- SERVICIO : gestiona

@enduml

