@startuml
skin rose
title Caso de Uso: Crear Usuario

state DASHBOARD_ABIERTO as "DASHBOARD_ABIERTO"
state CrearUsuario as "Crear Usuario"
state IngresarDetallesUsuario as " "
state ConfirmarCreacionUsuario <<choice>>

[*] --> DASHBOARD_ABIERTO
DASHBOARD_ABIERTO -[#blue]-> CrearUsuario : El sistema permite solicitar 'Crear Usuario'
CrearUsuario -[#blue]-> IngresarDetallesUsuario : El administrador selecciona opción 'Crear Usuario'
IngresarDetallesUsuario -[#blue]-> ConfirmarCreacionUsuario : El administrador introduce detalles
ConfirmarCreacionUsuario -[#blue]-> DASHBOARD_ABIERTO : [Creación confirmada]
ConfirmarCreacionUsuario -[#red]-> DASHBOARD_ABIERTO : [Creación cancelada]

note right of IngresarDetallesUsuario
  El sistema permite:
  - Introducir nombre de usuario
  - Introducir datos personales
  - Introducir credenciales
  - Introducir tipo de contrato
end note

@enduml