@startuml
skin rose
title Caso de Uso: Editar Usuario

state DASHBOARD_ABIERTO

DASHBOARD_ABIERTO --> editarUsuario

state editarUsuario {
  [*] -[#blue]-> seleccionarUsuario
  state "Seleccionar usuario a editar" as seleccionarUsuario
  seleccionarUsuario -[#blue]-> modificarDetallesUsuario
  state "Modificar detalles del usuario" as modificarDetallesUsuario
  modificarDetallesUsuario -[#blue]-> [*]
  note on link: El administrador confirma la edición
  
  seleccionarUsuario -[#red]-> [*]
  note on link: El administrador cancela la edición
}

note left of modificarDetallesUsuario
  El sistema permite:
  ° Modificar nombre de Usuario
  ° Modificar datos personales
  ° Modificar tipo de contrato
  ° Modificar credenciales
  ° Confirmar edición
end note

note left of seleccionarUsuario
  El sistema requiere:
  ° Buscar Usuario por nombre
  ° Seleccionar Usuario de la lista
end note

@enduml
