@startuml
skin rose
title Caso de Uso: Eliminar Usuario

state DASHBOARD_ABIERTO

DASHBOARD_ABIERTO --> eliminarUsuario

state eliminarUsuario {
  [*] -[#blue]-> seleccionarUsuario
  state "Seleccionar usuario para eliminar" as seleccionarUsuario
  seleccionarUsuario -[#blue]-> confirmarEliminarUsuario
  state "Confirmar eliminación del usuario" as confirmarEliminarUsuario
  confirmarEliminarUsuario -[#blue]-> [*]
  note on link: El administrador confirma la eliminación
  
  seleccionarUsuario -[#red]-> [*]
  note on link: El administrador cancela la eliminación
}

note left of confirmarEliminarUsuario
  El sistema permite:
  ° Confirmar eliminación del usuario
  ° Mostrar ventana con la lista de usuarios eliminados
end note

note left of seleccionarUsuario
  El sistema requiere:
  ° Buscar Usuario por nombre
  ° Seleccionar Usuario de la lista
end note

@enduml
