@startuml
skin rose
title Caso de Uso: Iniciar Sesión

state INICIO as "INICIO"
state DASHBOARD_ABIERTO as "DASHBOARD_ABIERTO"
state Validar <<choice>>
state MostrarError as " "

[*] --> INICIO

INICIO -d[#blue]-> Login : El sistema presenta formulario de inicio de sesión
Login -d[#blue]-> Validar : El usuario introduce credenciales
Validar -d[#blue]-> DASHBOARD_ABIERTO : [Credenciales correctas]
Validar -r[#red]-> MostrarError : [Credenciales incorrectas]
MostrarError -r[#red]-> INICIO : El sistema muestra error

note left of Login
  El sistema muestra campos para:
  - Nombre de usuario
  - Contraseña
end note

@enduml
