@startuml
skin rose
title Caso de Uso: Cerrar Sesión

state DASHBOARD_ABIERTO as "DASHBOARD_ABIERTO"
state INICIO as "INICIO"
state ConfirmarCierre <<choice>>
state CancelarCierre as " "

[*] --> DASHBOARD_ABIERTO

DASHBOARD_ABIERTO -d[#blue]-> Logout : El usuario solicita cerrar sesión
Logout -d[#blue]-> ConfirmarCierre : El sistema presenta opciones para confirmar cierre de sesión
ConfirmarCierre -d[#blue]-> INICIO : [Cierre confirmado]
ConfirmarCierre -r[#red]-> CancelarCierre : [Cierre cancelado]
CancelarCierre -r[#red]-> DASHBOARD_ABIERTO : El sistema cancela cierre



@enduml
