@startuml
left to right direction
skinparam packageStyle rectangle


rectangle OPENED_DASHBOARD {

}


rectangle FICHAJE {
    getFichaje --> Inicio
    Inicio --> Tiempo : calculateTime
    Inicio --> NumeroFichajes : getTotalFichajes
    Tiempo --> ViewTiempo : showTime
    ViewTiempo --> Inicio
    

}

rectangle INFORME {

}
rectangle EXIT {

}

OPENED_DASHBOARD -> FICHAJE: getFichaje
FICHAJE -> INFORME : verInforme
FICHAJE -> EXIT : logOut



@enduml