@startuml Caso de Uso: Ver Fichaje
skin rose

title Caso de Uso: Ver Fichaje

start
:DASHBOARD ABIERTO;
-> El sistema muestra el fichaje diario;
:VER FICHAJE DIARIO;
-> El sistema muestra horas de fichaje;
:                            ;
-> El sistema calcula horas trabajadas;
:                            ;
-> El sistema calcula horas restantes para la jornada;
:                            ;
-> Usuario/Admin revisa la información;
:                            ;
stop

@enduml