@startuml
skin rose
title Caso de Uso: Ver Informe (Admin)

state DASHBOARD_ABIERTO as "DASHBOARD_ABIERTO"
state ListaUsuarios as "Ver Usuario"
state SeleccionarUsuario <<choice>>
state TipoInforme <<choice>>
state MostrarInforme as "Mostrar Informe"

[*] -d-> DASHBOARD_ABIERTO
DASHBOARD_ABIERTO -d[#blue]-> ListaUsuarios : El sistema muestra lista de usuarios
ListaUsuarios -d[#blue]-> SeleccionarUsuario : El sistema permite solicitar un usuario
SeleccionarUsuario -r[#blue]-> TipoInforme : [Usuario seleccionado]
TipoInforme -d[#blue]-> MostrarInforme : El admin introduce Tipo de informe y rango
SeleccionarUsuario -l[#red]-> DASHBOARD_ABIERTO : [Selección cancelada]
TipoInforme -l[#red]-> DASHBOARD_ABIERTO : [Selección de informe cancelada]
MostrarInforme -d[#blue]-> DASHBOARD_ABIERTO : El admin cierra informe

note right of TipoInforme
  El sistema permite:
  - Introducir tipo de informe
  - Introducir rango de fechas
end note

note right of MostrarInforme
  El sistema:
  - Presenta el informe
  - Permite solicitar dejar de ver el informe
end note

@enduml
