@startuml descripción CDU informe

skin rose
title Caso de Uso: Ver Informe

state DASHBOARD_ABIERTO

DASHBOARD_ABIERTO --> verInforme

state verInforme {
  [*] -[#blue]-> inicioInforme
  state " " as inicioInforme
  inicioInforme -[#blue]-> mostrarInforme
  note on link: EL usuario selecciona tipo de informe y rango de fechas
  inicioInforme -[#red]-> [*]
  note on link: El usuario cancela el ver informe

  state " " as mostrarInforme
  mostrarInforme -[#blue]-> inicioInforme
  note on link: El usuario repite la busqueda
  mostrarInforme -[#blue]-> [*]
  note on link: El usuario cierra el informe
  
}

note left of inicioInforme
  El sistema solicita:
  ° Seleccionar Tipo de informe
  ° Seleccionar Rango de fechas
  El sistema permite:
  ° Realizar la busqueda
  ° Cancelar la busqueda
end note

note bottom of mostrarInforme
  El sistema permite:
  ° Descargar el informe
  ° Repetir la busqueda
  ° Cerrar el informe
  El sistema muestra si existe el informe
end note

@enduml
