@startuml
skin rose
title Caso de Uso: Ver Usuario

state DASHBOARD_ABIERTO as "DASHBOARD_ABIERTO"
state LeerUsuarios as "Ver Usuarios"
state SeleccionarUsuario <<choice>>
state VisualizarPerfil as " "


[*] --> DASHBOARD_ABIERTO
DASHBOARD_ABIERTO -[#blue]-> LeerUsuarios : El administrador solicita ver Usuarios
LeerUsuarios -[#blue]-> SeleccionarUsuario : El sistema presenta lista de usuarios
SeleccionarUsuario -[#blue]-> VisualizarPerfil : [Usuario seleccionado]
VisualizarPerfil -[#blue]-> DASHBOARD_ABIERTO : El sistema muestra perfil del usuario
SeleccionarUsuario -[#red]-> DASHBOARD_ABIERTO : [Visualización cancelada]

note right of VisualizarPerfil
  El sistema muestra:
  - Datos personales del usuario
  - Tipos de contrato del usuario
  - Opciones para editar, eliminar o añadir usuario
end note

note left of SeleccionarUsuario
  El sistema permite:
  - Introducir el nombre de usuario
  - Seleccionar usuario de la lista
  - Cancelar búsqueda
end note



@enduml
