@startuml
skin rose
title Caso de Uso: Ver Usuario

state DASHBOARD_ABIERTO as "DASHBOARD_ABIERTO"
state LeerUsuarios as "Ver Usuarios" 
  
state SeleccionarUsuario <<choice>>
state VisualizarPerfil as " "


[*] -d-> DASHBOARD_ABIERTO
DASHBOARD_ABIERTO -d[#blue]-> LeerUsuarios : El administrador solicita ver Usuarios
LeerUsuarios -d[#blue]-> SeleccionarUsuario : El sistema presenta lista de usuarios
SeleccionarUsuario -r[#blue]-> VisualizarPerfil : [Usuario seleccionado]
VisualizarPerfil -d[#blue]-> DASHBOARD_ABIERTO : El sistema muestra perfil del usuario
SeleccionarUsuario -l[#red]-> DASHBOARD_ABIERTO : [Visualización cancelada]

note right of VisualizarPerfil
  El sistema muestra:
  - Datos personales del usuario
  - Tipos de contrato del usuario
  - Opciones para editar, eliminar o añadir usuario
end note

note left of SeleccionarUsuario
  El sistema permite:
  - Introducir el nombre de usuario
  - Seleccionar usuario de la lista
  - Cancelar búsqueda
end note



@enduml
