@startuml
skinparam defaultFontName Arial
top to bottom direction

[*] --> NoRegistrado : Inicio

state NoRegistrado {
  state Procesando <<choice>>
  [*] --> Procesando : Egresado introduce sus datos
  Procesando --> Registrado : Encontrado en BD Uneatlantico
  Procesando --> NoRegistrado : Egresado no encontrado
}

state Registrado {
  [*] --> [*] : Mostrar página de login
}
@enduml
