@startuml Contexto
title Contexto Egresado

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
[*] --> REGISTRAR_EGRESADO
INICIAR_SESIÓN --> INICIO : Iniciar Sesión
REGISTRAR_EGRESADO --> INICIO : Registrar Egresado

REGISTRAR_EGRESADO -> REGISTRO_EN_PLATAFORMA
REGISTRAR_EGRESADO <- REGISTRO_EN_PLATAFORMA

INICIO --> [*] : Cerar Sesión

@enduml