@startuml CRUD_Suscription
left to right direction

title CRUD Suscripción

folder "CRUD Suscripción" {
    actor Egresado

    Egresado --> (Listar Servicios/Paquetes)
    Egresado --> (Suscripción a Servicio/Paquete)
    Egresado --> (Editar Suscripción de Servicio/Paquete)
    Egresado --> (Eliminar Suscripción de Servicio/Paquete)
}

@enduml