@startuml
title CRUD Suscripción

state "Listar Servicios/Paquetes" as ListServicesPackages
state "Suscripción a Servicio/Paquete" as SubscribeServicePackage
state "Editar Suscripción de Servicio/Paquete" as EditSubscriptionServicePackage
state "Eliminar Suscripción de Servicio/Paquete" as DeleteSubscriptionServicePackage

[*] --> ListServicesPackages
ListServicesPackages --> SubscribeServicePackage : seleccionar servicio/paquete
SubscribeServicePackage --> EditSubscriptionServicePackage : editar suscripción
SubscribeServicePackage --> DeleteSubscriptionServicePackage : eliminar suscripción
EditSubscriptionServicePackage --> ListServicesPackages : guardar cambios
DeleteSubscriptionServicePackage --> [*] : confirmar la eliminación

@enduml