@startuml Contexto
title Contexto General

skinparam {
    NoteBackgroundColor #whiteSmoke
    NoteBorderColor #green
    linetype polyline
}

hide empty description

[*] --> INICIAR_SESIÓN
INICIAR_SESIÓN --> INICIO : Iniciar Sesión

INICIO -> SERVICIOS
INICIO <- SERVICIOS

SERVICIOS -> REALIZAR_PETICION
SERVICIOS <- REALIZAR_PETICION
SERVICIOS -> LISTAR_SERVICIOS_PAQUETES
SERVICIOS <- LISTAR_SERVICIOS_PAQUETES

INICIO --> [*] : Cerar Sesión

@enduml