@startuml

  (*) -->  Cliente utiliza el Core
    if "¿Existe Error?" then
      -->[Si] Administrador Recibe Ticket
      --> Administrador Asigna Desarrollador
      --> Desarrollador da Seguimiento al Ticket
      --> Desarrollador Solventa Error
      --> Administrador Valida la Solución
      if "¿Solucion Validada?" then
        -->[Si] Administrador Cierra Ticket
        --> (*)
        else
        -->[No] Desarrollador da Seguimiento al Ticket
      endif
    else
    -->[No] (*)
    endif

@enduml