[*] --> ServicioActivo : se crea un servicio

ServicioActivo--> ServicioInactivo : se desactiva un servicio
ServicioInactivo--> ServicioActivo : se reactiva un servicio
State ServicioActivo{
[*]-->Servicio
Servicio-->AñadidoaPaquete :se añade el servicio a un paquete
AñadidoaPaquete --> Servicio : se elimina el servicio del paquete}


@enduml