@startuml
title Asignación de Asignaturas

actor GestorAsignaciones
entity Asignatura
entity Docente

GestorAsignaciones --|> Asignatura: asignarAsignaturaDocente()
Asignatura --> Docente: asignado a

@enduml