@startuml
title Asignación de Docentes a Cursos

actor Administrador

Administrador --> (Identificar Docentes No Asignados)
Administrador --> (Comenzar Asignación)
(Comenzar Asignación) --> (Asignar Docente a Curso)
(Asignar Docente a Curso) --> (Todos los Docentes Asignados) : Si
(Asignar Docente a Curso) --> (Identificar Docentes No Asignados) : No

@enduml
