@startuml
title Creación de un Horario de Clases

state "HorarioNoCreado" as HorarioNoCreado
state "Creando" as Creando
state "HorarioFinalizado" as HorarioFinalizado

[*] --> HorarioNoCreado
HorarioNoCreado --> Creando : Asignar Clases, Profesores y Aulas
Creando --> HorarioFinalizado : Todas las Asignaciones Completas y sin Conflictos
HorarioFinalizado --> [*] : Finalizar Creación del Horario

@enduml
