@startuml

skinparam state {
  BackgroundColor #e6ee9c
  BorderColor #d32f2f
}

skinparam note {
  BackgroundColor #ffe0b2
}

skinparam linetype polyline

title Caso de Uso - Guardado de Cambios en Sistema TimeGuardian

INICIO -[#red]-> sistema_timeguardian
note on link
  **Sistema TimeGuardian:**
  - Proceso de guardado de cambios
end note

sistema_timeguardian -[#red]-> guardar_cambios_realizados
note right of guardar_cambios_realizados
  Guardar cambios realizados
end note

guardar_cambios_realizados -[#red]-> actualizar_información_horario
note on link
  **Sistema realiza:**
  - Actualizar información del horario
end note

actualizar_información_horario -[#red]-> hacer_accesible_información_actualizada
note right of hacer_accesible_información_actualizada
  Hacer accesible la información actualizada
end note

hacer_accesible_información_actualizada -[#red]-> [*]

@enduml
