@startuml

skinparam state {
  BackgroundColor #e6ee9c
  BorderColor #004d40
}

skinparam note {
  BackgroundColor #ffe0b2
}

skinparam linetype polyline

title Caso de Uso - Creación de Asignatura

[*] -[#green]-> inicio
note right of inicio
  **Coordinador académico inicia:**
  - Proceso de creación de asignatura
end note

inicio -[#green]-> definir_parametros_asignatura
note right of definir_parametros_asignatura
  Definir parámetros de la asignatura
end note

definir_parametros_asignatura -[#green]-> crear_plan_estudio
note on link
  **Coordinador define:**
  - Contenidos y evaluaciones de la asignatura
end note

crear_plan_estudio -[#green]-> confirmar_creación
note on link
  **Coordinador confirma:**
  - Creación de la asignatura
end note

confirmar_creación -[#green]-> [*]
note right of confirmar_creación
  Asignatura creada y lista para ser incluida en el programa académico
end note

@enduml
