@startuml
actor "Administrador de horarios" as A
participant "Sistema TimeGuardian" as S

A -> S : Inicia sesión en el sistema
activate S
S --> A : Muestra la interfaz principal
deactivate S
activate A
A -> S : Selecciona la opción para visualizar las asignaturas ofrecidas para una carrera específica
deactivate A
activate S
S --> A : Muestra las asignaturas ofrecidas para la carrera seleccionada
deactivate S
activate A
A -> S : Arrastra y suelta las asignaturas en el calendario
deactivate A
activate S
S --> A : Guarda los cambios y actualiza el horario académico de los estudiantes
deactivate S
@enduml
