@startuml AumniClasses

title Diagrama de Clases

'!theme amiga
skinparam backgroundColor white
skinparam defaultFontName Arial

class PLATAFORMA 
{
   Alumni
}

abstract "SERVICIO EXTERNO" {}

abstract USUARIO 
{
    ID
    Nombre 
    Apellido
    Fecha de Nacimiento
    Email
}

class EGRESADO 
{
    Ubicacion
    Ocupación
    Carnet de Estudiante
}

class ADMINISTRADOR 
{
    Zona de trabajo
}

class REQUISITO 
{
    Titulación de UNEAT
}

class ESTADISTICA 
{
}

class SUSCRIPCIÓN 
{
    Paquetes Suscritos
    Servicios Suscritos
    Precio Total
}

class PAQUETE
{
    Nombre
    Descripción
    Servicios incluidos
    Precio
}

abstract SERVICIO 
{
    Nombre 
    Descripción
    precio
    tipo de servicio
}

PLATAFORMA -- USUARIO : tiene
PLATAFORMA - ESTADISTICA : genera
SUSCRIPCIÓN -up- PLATAFORMA : tiene
PLATAFORMA -left- "SERVICIO EXTERNO" : se comunica
SUSCRIPCIÓN -- SERVICIO : incluye
EGRESADO -- REQUISITO : cumple
SUSCRIPCIÓN -- PAQUETE : incluye
PAQUETE - SERVICIO : incluye
USUARIO <|-- EGRESADO
USUARIO <|-left- ADMINISTRADOR
ADMINISTRADOR -up- PLATAFORMA : administra

@enduml

